version: '3.7'

services:

  php:
    build:
      context: ./docker
    ports:
      - 9000:9000
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./docker/php/.env:/var/www/wordpress/.env
#      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./log:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
